baseurl = "http://localhost:1313/"
languageCode = "en-us"
title = "#carajam"
theme = "strange-case"
description = "A Hugo Theme built with Bootstrap"

[params]
    DateFormat = "2 Jan 2006"
    description = "Save the handmade music"
    sidebarDescription = "A Hugo Theme built with Bootstrap"
    sidebarFreeText = "A optional paragraph of free text. Set to blank in config.toml to clear..."
