baseurl = "https://carajam.netlify.com/"
languageCode = "en-us"
title = "carajam"
theme = "strange-case"
description = "We are touring around europe with our caravan and organising "

[params]
    DateFormat = "2 Jan 2006"
    description = "Save the handmade music"
    sidebarDescription = "—"
    sidebarFreeText = "Playing the piano and living a traveling lifestyle seemed always impossible to me, untill I put my piano in an old caravan."
