baseurl = "https://carajam.netlify.com/"
languageCode = "en-us"
title = "carajam"
theme = "strange-case"
description = "We are touring around europe with our caravan and organising "

[params]
    DateFormat = "2 Jan 2006"
    description = "Save the handmade music"
    sidebarDescription = "Save the handmade music"
    sidebarFreeText = "Traveling europe with a Piano in a camping car to fight the dark force of not hand made music."
